GoGo-Ring/dongoorami-frontend

- hooks/useForm.ts
> 제어 방식의 useForm 을 구현하였습니다.
공용 hooks 폴더에다 넣는게 맞을까요?? 아니면, _hooks 로 해당 세그먼트에 위치시켜야할까요??
close #25
> Feat: [#25] 폼 상태 관리 및 유효성 검사를 위한 useForm 구현

- app/providers.tsx
- tanstack-query의 queryClientProvider를 사용하기 위한 파일을 생성했습니다.
- QueryClientProvider는 클라이언트 사이드에서 동작하지만, next.js의 root layout은 서버 사이드 컴포넌트이기 때문에 별도 파일을 생성하여 queryClient를 제공합니다!
- close #36
> Chore: [#36] tanstack-query provider 추가

- app/layout.tsx
fontSans의 export 키워드를 제거합니다.
- close #46
> Fix: [#46] export 키워드 제거

- app/_components/CompanionRecruitmentCard.tsx
- utils/dateFormatter.ts
- props를 자식 컴포넌트에 전달하던 방식에서 contextAPI로 전달하도록 수정했습니다.
- API 명세서에 따라 필드명을 수정했습니다.
- getDate 함수에 'yyyy.mm.dd'형식을 추가했습니다.
```javascript
<CompanionRecruitmentCard
title="글제목글제목글제목글제목글제목글제목글제목글제목글제목글제목"
concertName="공연명공연명"
userId="사용자id"
gender="무관"
personCount={1}
viewCount={2}
commentsCount={3}
date={new Date()}
status={'모집 중'}
/>
```
- close #41 
- contextAPI를 올바르게 사용했는지 궁금합니다.
- defaultValue에 적절하게 작성했는지 궁금합니다.
> Refactor: [#41] 동행 구함 카드 컴포넌트 내부에 props 전달

- apis/member.ts
- app/login/_components/oauth-button/o-auth-button.tsx
- app/login/_components/oauth-button/utils.ts
- app/login/page.tsx
- app/register/page.tsx
소셜로그인 버튼 클릭 시 리다이렉션 uri를 지정 및 이동 해줬던 방식에서
get요청을 보내도록 백엔드에 맞춰 수정하였습니다.
로그인 테스트버튼을 삭제했습니다.
회원가입 request field에서 nickname을 받지 않고 있어 임시로 데이터를 전송하지 않도록 수정하였습니다.
회원가입 시 post요청을 patch 로 수정하였습니다.
- close #80 
빠른 머지 가능할 것 같습니다!
> Feat: [#80] 소셜로그인 버튼 클릭 시 로그인 요청 방식 수정, 회원가입 form 수정

- app/_components/CompanionRecruitmentCard.tsx
- 동행 구함 카드 컴포넌트에 eye, chat icon을 추가했습니다.
- 기본 색상에서 gray 색상으로 변경했습니다.
- commentsCount 와 viewCount의 위치를 서로 바꾸었습니다.
- close #73
> Refactor: [#73] 동행 구함 카드 컴포넌트에 icon 추가

- app/_components/filter-field/button-select.tsx
- app/_components/filter-field/checkbox-select.tsx
Button-select 컴포넌트 오류 수정
- close #91
> Fix: [#91] Button-select 컴포넌트 오류 수정

- app/_components/companion-recruitment-filter.tsx
동행 구함 필터의 options 객체, 체크박스의 fieldName을 수정했습니다.
- close #105
> Fix: [#105] 동행 구함 필터의 options 객체, 체크박스의 fieldName 수정

- app/recruitment/new/_components/page-skeleton.tsx
- app/recruitment/new/error.tsx
- app/recruitment/new/loading.tsx
- app/recruitment/new/page.tsx
구인 입력 페이지에 수정 정보가 들어올시 대비하여, 로딩처리와 에러처리를 하였습니다.
-  스켈레톤 ui
-  로딩 처리, 에러처리
-  tailwind config 너비에 맞추기
- close #77
> Feat: [#77] 구인 입력 페이지 에러와 로딩 처리

- app/recruitment/[id]/_components/comment/form.tsx
- app/recruitment/new/_components/fields/calendar-field.tsx
- app/recruitment/new/_components/fields/slider-field.tsx
- app/recruitment/new/_components/form.tsx
- app/recruitment/new/constants.ts
- hooks/useForm/index.ts
- hooks/useForm/types.ts
useForm 을 리팩토링 합니다.
- close #101 
- useForm params 를 키와 value 값인 객체로 받아, 가독성을 높임
- 간단한 submit(handleChange 사용안하는) 을 위한 비제어 submit, handleUncontrolledSubmit 함수 추가
- validationRulesList 를 useForm params 로 받음
- 리팩토링된 훅, 구인 입력,구인 정보 댓글에 적용
- useForm 내부 리팩토링
```ts
const { handleUnContolledSubmit } = useForm({
initialValues: { comment: '' },
onSubmit: values => {
mutate({ userId: '1', content: values.comment });
},
validationRulesList: [
{
id: 'comment',
validate: value => value.trim().length > 0,
message: '댓글을 입력하세요',
},
],
});
return (
<form onSubmit={handleUnContolledSubmit} className="flex flex-col gap-7">
```
> Refactor: [#101] useForm 리팩토링

- apis/scheme/accompany.ts
- app/recruitment/[id]/_components/apply.tsx
- app/recruitment/[id]/_components/post-status.tsx
- app/recruitment/[id]/page.tsx
- mocks/handlers/accompany.ts
공연 상세 페이지의 누락된 ui 를 추가하였습니다.
- 수정 삭제 링크 추가
- 모집 상태 뱃지 추가
- 동행 신청 컴포넌트 추가
유저 관련 로직은 아직 정해지지 않았습니다.
- 유저에 따라 수정 삭제, 링크 노출 여부
- 유저 id 를 활용한, 쪽지 보내기 링크 불가
- close #110
> Feat: [#110] 공연 상세페이지 ui 추가

- components/header/index.tsx
- 헤더의 아이콘에 네비게이팅 기능을 추가합니다.
- 유저 페이지의 경우 현재는 PR 머지가 되지 않아 에러가 발생하지만, 추후 변경사항이 반영되면 정상적으로 동작할 것으로 보입니다.
- close #126
> Refactor: [#126] 헤더 아이콘 네비게이팅 주소 추가

- utils/starRating.ts
- close #146
1. `문제상황` string[]요소가 string이어서, Type 'filled' is not assignable to type "filled" 오류가 발생했습니다.
2. `수정사항` FilledType[]을 반환하도록 수정했습니다.
혹시 수정한 방법 외에 다른 방법이 있을까요?
> Fix: [#146] 타입 수정된 부분 재 반영

- package.json
프리뷰 사이트에 netlify handler 확장자 오류로인해 package module type 을제거하여 해결합니다.
- 패키지 모듈 타입 제거
- close #161
> Fix: [#161] package module type 제거

- app/_components/companion-recruitment-filter.tsx
- app/_components/filter-field/checkbox-select.tsx
- constants/filterField.ts
동행 구함 필터의 동행 목적에 대한 항목을 추가합니다
- 체크박스 선택 필드를 추가
- 동행 목적 나열
- checkbox-select 컴포넌트에 className prop을 추가
- 상수 배열에 목적 추가
- query를 만들기 위한 objectToQueryString을 이후 수정하려고 합니다.
- close #157
> Feat: [#157] 동행 구함 필터의 동행 목적에 대한 항목을 추가합니다

- apis/accompany.ts
- apis/scheme/accompanyInput.ts
- app/recruitment/new/_components/fields/search-button-field.tsx
- hooks/queries/useFetchCompanionPerformances.ts
- mocks/handlers/accompanyPerformances.ts
- mocks/handlers/index.ts
동행 입력 페이지의 공연 search 입력 컴포넌트를 위한 msw 와 api 함수 를 추가하였습니다.
- close #149
> Feat: [#149] 동행 입력 페이지에 공연 목록 search 입력을 위한 msw와 api 추가

- app/message/write/_components/list.tsx
- app/message/write/_components/page-skeleton.tsx
- app/message/write/error.tsx
- app/message/write/loading.tsx
- app/message/write/page.tsx
- app/recruitment/[id]/error.tsx
- app/recruitment/new/error.tsx
- components/header/index.tsx
- hooks/useForm/index.ts
- mocks/handlers/members.ts
쪽지 페이지에서 error.tsx 와 loading.tsx 로 에러처리와 로딩처리를 합니다.
- error.tsx
- loading.tsx
- ui 리팩토링
- 스켈레톤 추가
- close #153
> Feat: [#153] 쪽지 페이지 에러 처리 및 로딩처리

- components/header/mobile-nav.tsx
- mocks/handlers/index.ts
1. 슬라이드 sheet 라우팅 경로 수정 합니다
2. mocks handler 추가합니다
- close #186
> Chore [#186] 슬라이드 sheet 라우팅 경로 수정, mocks handler 추가

- app/review/[id]/page.tsx
- app/review/_components/review-form.tsx
- mocks/handlers/accompanyReview.ts
- 동행 리뷰 컴포넌트 width 수정했습니다.
- mock 데이터 수정했습니다.
- close #190
> Style [#190] 동행 리뷰 컴포넌트 width 수정

- components/header/main-nav.tsx
- components/header/mobile-nav.tsx
동행 글 작성하기 버튼을 헤더에 추가합니다. 
- close #189
> Feat: [#189] 동행 글 작성하기 버튼을 헤더에 추가합니다. 

- app/auth.tsx
인증되지 않은 유저를 리다이렉트 할 때 `router.push`가 아닌, `redirect` 함수를 사용합니다.
- redirect 함수는 router.push와 다르게 클라이언트 컴포넌트, 서버 컴포넌트 모두에서 사용 가능하다고 합니다.
- close #194
> Fix: [#194] 인증되지 않은 유저 리다이렉트

- app/recruitment/new/page.tsx
동행 페이지의 ui 를 리팩토링합니다.
- 동행 입력페이지의 모바일 뷰에서 field 갭을 줄입니다.
- 동행 입력페이지의 교통 수단 레이블을 동행 목적으로 변경합니다.
- close #187
> Refactor: [#187] 동행 페이지 ui 관련 수정

- apis/accompany.ts
- apis/index.ts
어떤 버그인가요?
어떤 상황에서 발생한 무슨 버그인지 설명해주세요
cors 버그입니다.
이미지를 가져올때, authoration 을 적용되어 발생하는 문제입니다.
- close #200
> Fix: [#200] cors 버그 

- app/_components/companion-recruitment-filter.tsx
- app/_components/filter-field/input-field.tsx
- constants/filterField.ts
동행 구인 필터 항목을 수정합니다.
- 이에 따라 region의 타입을 string[] 에서 string으로 수정했습니다.
- 만약 지역에 상관 없이 필터링 하고 싶은 경우를 위해, '무관' 추가했습니다.
- 목적이 추가되면서 교통 수단 항목이 삭제되었습니다.
- close #197
> Refactor: [#197] 동행 구함 필터 수정

- apis/accompany.ts
어떤 버그인가요?
cors error
예상 결과
cors error 해결
예상되는 정상적인 결과에 대해 설명해주세요
- close #204
> Fix: [#204] cors error

- app/message/_components/mobile-list.tsx
- app/users/[id]/page.tsx
- 쪽지 보내기 버튼 클릭 및 모바일 환경의 메시지 단건 클릭 시 메시지 작성 페이지로 이동합니다.
- 모바일 환경에서의 더미 쪽지를 제거합니다.
- close #206
> Fix: [#206] 메시지 전송 페이지 연결

- app/users/[id]/page.tsx
- app/users/_components/recieved-review.tsx
- 다른 유저 페이지에서 받은 후기 목록을 확인할 수 있습니다.
- close #209
> Feat: [#209] 받은 후기 목록 컴포넌트 추가

- app/recruitment/[id]/_components/apply/list.tsx
- app/recruitment/[id]/page.tsx
- hooks/mutations/useMutationCreateCompanyComment.ts
신청자도 신청자 목록 볼수있게 변경
waiting count 적용,
revalidate 적용
- close #207
> Feat: [#207] 동행 신청 시 보여지는 ui 로직 변경 

- app/recruitment/[id]/page.tsx
교통 수단 label 을 동행 목적으로 수정합니다.
- close #212 
전에 바꾼것 같은데,, 늦어져서 죄송합니다..
> Style: [#212] 교통 수단 -> 동행 목적 
